public enum Command {
	PLAY_LAST_SONG, PLAY_NEXT_SONG,
	MOVE_TO_SONG_LOCATION,
	RESTART_SONG, RESTART_QUEUE,
	PAUSE_SONG, PLAY_SONG,
	REPEAT_CURRENT_SONG, SHUFFLE,
	MAKE_SLOWER, MAKE_FASTER,
	LOUDER, QUIETER,
	DO_NOTHING, END_APPLICATION,
}